[package]
name = "yin-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
half = {version = "2.4.1", features = ["num-traits"]}
hound = "3.5.1"
num-traits = "0.2.19"
